# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches:
      - main
      - dev
      - testing
  pull_request:
    branches:
      - dev
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter
      uses: subosito/flutter-action@v1.3.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Install app dependencies
      run: chmod +x ./ci/flutter-pubget.sh && ./ci/flutter-pubget.sh
    - name: Test app
      run: chmod +x ./ci/test-app.sh && ./ci/test-app.sh
